### ISSUE TITLE
how does this plugin work with scss module?

### ISSUE THREAD

**Issue by ianzone** [ModyQyW/vite-plugin-stylelint#10]
the scss module source code is:
.myClassName {
  background-color: grey;
}

the error I got while using this plugin: 
[vite] Internal server error: Expected class selector to be kebab-case
  Plugin: vite:stylelint
  File: /home/ian/templates/react/src/components/MyComponent/style.module.scss
  1  |  ._myClassName_1x6hz_1 {
     |   ^
  2  |    background-color: grey;
  3  |  }
      at formatError (/home/ian/templates/react/node_modules/.pnpm/vite@2.9.9_sass@1.52.1/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38663:46)
      at TransformContext.error (/home/ian/templates/react/node_modules/.pnpm/vite@2.9.9_sass@1.52.1/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38659:19)
      at /home/ian/templates/react/node_modules/.pnpm/vite-plugin-stylelint@2.2.3_wtr3vw7wiz4253njg4veakonmm/node_modules/vite-plugin-stylelint/dist/index.js:1:2442
      at Array.forEach (<anonymous>)
      at /home/ian/templates/react/node_modules/.pnpm/vite-plugin-stylelint@2.2.3_wtr3vw7wiz4253njg4veakonmm/node_modules/vite-plugin-stylelint/dist/index.js:1:2320
      at Array.forEach (<anonymous>)
      at /home/ian/templates/react/node_modules/.pnpm/vite-plugin-stylelint@2.2.3_wtr3vw7wiz4253njg4veakonmm/node_modules/vite-plugin-stylelint/dist/index.js:1:2275
      at async TransformContext.transform (/home/ian/templates/react/node_modules/.pnpm/vite-plugin-stylelint@2.2.3_wtr3vw7wiz4253njg4veakonmm/node_modules/vite-plugin-stylelint/dist/index.js:1:2103)
      at async Object.transform (/home/ian/templates/react/node_modules/.pnpm/vite@2.9.9_sass@1.52.1/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38900:30)
      at async doTransform (/home/ian/templates/react/node_modules/.pnpm/vite@2.9.9_sass@1.52.1/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:55857:29)

**Comment by ModyQyW** [comment]
Can you please share your vite config or a minimal reproduction?

**Comment by ianzone** [comment]
Hi, I've uploaded the code to https://github.com/ianzone/react-template
I'm using pnpm v7.1.3 and node 18

**Comment by ModyQyW** [comment]
I just clone https://github.com/ianzone/react-template and `pnpm install && pnpm run dev`. No errors are shown. Is there anything missing?

By the way, I am using pnpm v7.1.5 and node v16.14.2. I don't think this should be a major influencing factor.

**Comment by ianzone** [comment]
Oh, I just added "selector-class-pattern": null into .stylelintrc.json to get rid of the error, it's not a plugin problem, thank you :)

**Comment by ModyQyW** [comment]
In fact, there are certain things I do care more about.

The source code is `.myClassName { ... }` but you can get the error including `._myClassName_1x6hz_1 { ... }`. The classname is changed. I will keep digging about this.

Also glad you get rid of this problem. Feel free to create another issue if you are facing a new problem.
