### ISSUE TITLE
No filename or line number?

### ISSUE THREAD

**Issue by johnnyshankman** [ModyQyW/vite-plugin-stylelint#21]
### Describe the bug

```
error when starting dev server:
Error: Unexpected duplicate "display" (declaration-block-no-duplicate-properties)
    at formatError (/Users/whatever/Documents/company/project/node_modules/vite/dist/node/chunks/dep-689425f3.js:39080:46)
    at Context.error (/Users/whatever/Documents/company/project/node_modules/vite/dist/node/chunks/dep-689425f3.js:39076:19)
    at /Users/whatever/Documents/company/project/node_modules/vite-plugin-stylelint/dist/index.js:1:2047
    at async S (/Users/whatever/Documents/company/project/node_modules/vite-plugin-stylelint/dist/index.js:1:1627)
    at async Context.buildStart (/Users/whatever/Documents/company/project/node_modules/vite-plugin-stylelint/dist/index.js:1:2404)
    at async Promise.all (index 15)
    at async Object.buildStart (/Users/whatever/Documents/company/project/node_modules/vite/dist/node/chunks/dep-689425f3.js:39230:13)
    at async Server.httpServer.listen (/Users/whatever/Documents/company/project/node_modules/vite/dist/node/chunks/dep-689425f3.js:60350:21)
```

This output is completely garbled, even with sourcemaps inlined into my build. Why is there no filename or even a line number included in the report?

### Reproduction

Use SFC syntax in Vite. Add issue to the styles.

```
<template>
...
</template>
<script setup lang="ts">
// ...
});
</script>
<style lang="scss">
// ... errors in here
</style>
```

```
// my vite config
  // Note: Only For Production Build
  build: {
    sourcemap: 'inline',
    lib: {
      entry: path.resolve(__dirname, 'src/entry.ts'),
      formats: ['cjs', 'umd'],
      name: 'connect',
      fileName: 'connect',
    },
    rollupOptions: {
      output: {
        assetFileNames: 'connect.[ext]',
      },
    },
  },

  plugins: [
    vue(),
    checker({
      vueTsc: true,
    }),
    eslint({
      fix: true,
      lintOnStart: true,
      include: ['src/**/*.js', 'src/**/*.ts', '**/*.vue'],
    }),
    StylelintPlugin({
      lintOnStart: true,
      fix: true,
    }),
  ],
```

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.63 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.2/bin/yarn
    npm: 8.2.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by johnnyshankman** [comment]
Only small improvement is I've managed to get the line number by turning off some plugins but still, no file name.

```
  optimizeDeps: process.env.NODE_ENV === 'production' ? {
    esbuildOptions: {
      // Node.js global to browser's globalThis
      define: {
        global: 'globalThis',
      },
      // Enable Node.js polyfills
      plugins: [
        GlobalsPolyfills({
          process: true,
          buffer: true,
        })
      ],
    },
  } : {},
  
 ```
 
 Error:
 ```
error when starting dev server:
Error: Unexpected duplicate selector "button", first used at line 192 (no-duplicate-selectors)
    at formatError (/Users/person/Documents/place/repo/node_modules/vite/dist/node/chunks/dep-689425f3.js:39080:46)
    at Context.error (/Users/person/Documents/place/repo/node_modules/vite/dist/node/chunks/dep-689425f3.js:39076:19)
    at /Users/person/Documents/place/repo/node_modules/vite-plugin-stylelint/dist/index.js:1:2047
    at async S (/Users/person/Documents/place/repo/node_modules/vite-plugin-stylelint/dist/index.js:1:1627)
    at async Context.buildStart (/Users/person/Documents/place/repo/node_modules/vite-plugin-stylelint/dist/index.js:1:2404)
    at async Promise.all (index 15)
    at async Object.buildStart (/Users/person/Documents/place/repo/node_modules/vite/dist/node/chunks/dep-689425f3.js:39230:13)
    at async Server.httpServer.listen (/Users/person/Documents/place/repo/node_modules/vite/dist/node/chunks/dep-689425f3.js:60350:21)
    ````

**Comment by johnnyshankman** [comment]
When I restart my server while it's running I only get

```
Error: Unexpected duplicate "display" (declaration-block-no-duplicate-properties)
```

**Comment by ModyQyW** [comment]
I get this warning when I test on `examples/vue`. Obviously vite prints the file and line number.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/31850793/199364902-682ecb96-2dca-471f-b5ac-5f2404fce662.png">

I think something goes wrong. Can you kindly share a minimal reproducible repo? Thanks.

**Comment by ModyQyW** [comment]
@johnnyshankman Hi. Can you kindly share a minimal reproducible repo? Thanks.

**Comment by ModyQyW** [comment]
@johnnyshankman Hi. Can you kindly share a minimal reproducible repo? Thanks.

**Comment by ModyQyW** [comment]
I'm closing this because I can't reproduce the issue.

**Comment by ModyQyW** [comment]
Try v3.1.0
